expected_dictionary = {'Aliases for A': {0: '-'},
                       'Aliases for B': {0: '-'},
                       'Alternative identifier for interactor A': {0: '-'},
                       'Alternative identifier for interactor B': {0: '-'},
                       'Annotations for Interactor B': {0: 'end:protein;uniprotac;q9y5k6'},
                       'Annotations for interactor A': {0: 'start:protein;uniprotac;p22681'},
                       'Annotations for the interaction': {0: '-'},
                       'Biological role A': {0: '-'},
                       'Biological role B': {0: '-'},
                       'Checksum for interaction': {0: '-'},
                       'Checksum for interactor A': {0: '-'},
                       'Checksum for interactor B': {0: '-'},
                       'Complex expansion': {0: '-'},
                       'Confidence score': {0: '-'},
                       'Creation date': {0: '-'},
                       'Experimental role A': {0: '-'},
                       'Experimental role B': {0: '-'},
                       'Features for interactor A': {0: '-'},
                       'Features for interactor B': {0: '-'},
                       'First author': {0: '-'},
                       'Identifier of the publication': {
                           0: 'pudmed:12874286;pudmed:11067845;pudmed:15128873;pudmed:12559036;pudmed:12672817;pudmed:12618476;pudmed:22706086;pudmed:17188587;pudmed:17072306;pudmed:25036637;pudmed:25872741;pudmed:17020880'},
                       'Interaction detection methods': {0: ''},
                       'Interaction identifiers': {0: '-'},
                       'Interaction types': {0: ''},
                       'Interactor type A': {0: "psi-mi:'mi:326'(unknown)"},
                       'Interactor type B': {0: "psi-mi:'mi:326'(unknown)"},
                       'NCBI Taxonomy identifier for interactor A': {0: '-'},
                       'NCBI Taxonomy identifier for interactor B': {0: "taxid:9606 ('homo "
                                                                        "sapiens')"},
                       'NCBI Taxonomy identifier for the host organism': {0: '-'},
                       'Parameters of the interaction': {0: '-'},
                       'Participant identification method for interactor A': {0: '-'},
                       'Participant identification method for interactor B': {0: '-'},
                       'Source databases': {
                           0: 'psi-mi:"mi:463"(unknown)|psi-mi:"mi:468"(unknown)|psi-mi:"mi:469"(unknown)'},
                       'Stoichiometry for interactor A': {0: '-'},
                       'Stoichiometry for interactor B': {0: '-'},
                       'Unique identifier for interactor A': {0: 'uniprotac:p22681'},
                       'Unique identifier for interactor B': {0: 'uniprotac:q9y5k6'},
                       'Update date': {0: '-'},
                       'Xref for interactor A': {0: '-'},
                       'Xref for interactor B': {0: '-'},
                       'Xref for the interaction': {0: '-'},
                       'negative': {0: '-'}}
